[tool.poetry]
name = "mymodule"
version = "0.1.0"
description = ""
authors = ["rook <foo@bar>"]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.4.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
